# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the thirteen branch
on:
  push:
    branches: [ thirteen ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Start Building
        run: |
          wget https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh
          sudo -E bash android_build_env.sh
          git clone --depth=1 https://github.com/SuperiorOS-Devices/kernel_xiaomi_violet.git -b thirteen violet
          cd violet
          sudo -E bash build.sh
